server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
      username: emos
      password: emos
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456
  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: yangdi525@aliyun.com
    password: ax105105
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao: warn
  pattern:
     console: "%d{HH:mm:ss}  %-5level  %msg%n"
#secret秘钥 expire过期时间 cache-expire缓存过期时间
emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.1.7:3000/create_face_model
    checkinUrl: http://192.168.1.7:3000/checkin
#/192.168.1.7:300links主机ip地址
  email:
    system: 邮箱地址1
    hr: 邮箱地址2
    image-folder: E:/emos/image
    code: HelloWorld
    recieveNotify: http://PC电脑的IP地址:8080/emos-wx-api/meeting/recieveNotify
  image-folder: E:/emos/image
  code: HelloWorld

wx:
  app-id: wxba889b1c51863457
  app-secret: b155e4128225b8c32bbc540dd04cee30